baseURL: https://opentermsarchive.org/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
title: Open Terms Archive website
theme: opentermsarchive
disableKinds:
  - taxonomy
ignoreErrors: ["error-disable-taxonomy"]
removePathAccents: true
# Limit RSS feeds outputs by opt-in via front matter
outputs:
  home:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML
minify:
  tdewolff:
    html:
      keepQuotes: true
      keepComments: true
build:
  noJSConfigInAssets: true
