header:
  - name: Collections
    pageRef: /collections
    weight: 1
  - name: Publications
    pageRef: /publications
    weight: 2
  - name: Documentation
    url: https://docs.opentermsarchive.org
    weight: 3
  - name: Impact
    pageRef: /impact
    weight: 4
  - name: A propos
    pageRef: /about
    weight: 5
footer:
  - name: Accueil
    pageRef: /
    weight: 1
  - name: Collections
    pageRef: /collections
    weight: 2
  - name: Jeux de données
    pageRef: /datasets
    weight: 3
  - name: Publications
    pageRef: /publications
    weight: 4
  - name: Mémos
    pageRef: /memos
    weight: 5
  - name: Documentation
    url: https://docs.opentermsarchive.org
    weight: 6
  - name: Impact
    pageRef: /impact
    weight: 7
  - name: À propos
    pageRef: /about
    weight: 8
  - name: Contactez-nous
    identifier: mailto
    weight: 9
footer_sub:
  - name: État des services
    url: https://stats.uptimerobot.com/nXvrBcl0wx
    weight: 1
    params:
      target: _blank
  - name: Statistiques
    pageRef: /stats
    weight: 2
  - name: Principes de marque
    pageRef: /brand-guidelines
    weight: 3
  - name: Revue de presse
    pageRef: /press-review
    weight: 4
  - name: Présentations
    pageRef: /presentations
    weight: 5
  - name: Code source
    url: https://github.com/OpenTermsArchive/engine
    weight: 6
    params:
      target: _blank
  - name: Mentions légales
    pageRef: /legal-notice
    weight: 7
  - name: Politique de confidentialité
    pageRef: /privacy-policy
    weight: 8
